package br.unifae.engsof.poo3.gerenciadorDeTarefas.View;

public class Menu extends javax.swing.JFrame {


    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        btnCadastrar = new javax.swing.JMenu();
        TarefaPrazo = new javax.swing.JMenuItem();
        TarefaSimples = new javax.swing.JMenuItem();
        btnListar = new javax.swing.JMenu();
        ListarTarefas = new javax.swing.JMenuItem();
        btnSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCadastrar.setText("Cadastrar");

        TarefaPrazo.setText("Tarefa com prazo");
        TarefaPrazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TarefaPrazoActionPerformed(evt);
            }
        });
        btnCadastrar.add(TarefaPrazo);

        TarefaSimples.setText("Tarefa simples");
        TarefaSimples.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TarefaSimplesActionPerformed(evt);
            }
        });
        btnCadastrar.add(TarefaSimples);

        jMenuBar1.add(btnCadastrar);

        btnListar.setText("Listar");

        ListarTarefas.setText("Todas tarefas");
        ListarTarefas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarTarefasActionPerformed(evt);
            }
        });
        btnListar.add(ListarTarefas);

        jMenuBar1.add(btnListar);

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jMenuBar1.add(btnSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void ListarTarefasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarTarefasActionPerformed
        this.dispose();
        TelaListarTarefas lt = new TelaListarTarefas();
        lt.setVisible(true);
    }//GEN-LAST:event_ListarTarefasActionPerformed

    private void TarefaPrazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TarefaPrazoActionPerformed
        this.dispose();
        TelaCadastroPrazo tp = new TelaCadastroPrazo();
        tp.setVisible(true);
    }//GEN-LAST:event_TarefaPrazoActionPerformed

    private void TarefaSimplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TarefaSimplesActionPerformed
        this.dispose();
        TelaCadastro tc = new TelaCadastro();
        tc.setVisible(true);
    }//GEN-LAST:event_TarefaSimplesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ListarTarefas;
    private javax.swing.JMenuItem TarefaPrazo;
    private javax.swing.JMenuItem TarefaSimples;
    private javax.swing.JMenu btnCadastrar;
    private javax.swing.JMenu btnListar;
    private javax.swing.JMenu btnSair;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
